IS_MIRRORED: True

HANDEDNESS_FONT: 1
HANDEDNESS_FONT_SIZE: 2
HANDEDNESS_TEXT_COLOR: !!python/tuple [0, 0, 255]
HANDEDNESS_FONT_THICKNESS: 2
HANDEDNESS_LINE_TYPE: 16

HAND_BBOX_COLOR: !!python/tuple [255, 0, 0]
HAND_BBOX_THICKNESS: 1
HAND_BBOX_LINE_TYPE: 16

PALM_BBOX_COLOR: !!python/tuple [0, 0, 255]

PALM_BBOX_THICKNESS: 1
PALM_BBOX_LINE_TYPE: 16

FPS_ORIG: !!python/tuple [.015, .05]
FPS_FONT: 1
FPS_FONT_SIZE: 2
FPS_TEXT_COLOR: !!python/tuple [0, 0, 255]
FPS_FONT_THICKNESS: 2
FPS_LINE_TYPE: 16

BBOX_MARGIN: 10
PALM_MARGIN: 25
